# Pylearn2
#
# VERSION       0.1

# use the lucktroy/pylearn2
FROM lucktroy/pylearn2
MAINTAINER Junbo Zhang, zjb2046@gmail.com
# make sure the package repository is up to date
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" >> /etc/apt/sources.list
RUN apt-get update

ENTRYPOINT ["-v", "/tmp/regression-deep-learning:/media"]

RUN cd /media/example-pylearn2 && sh runMe2.sh
